### ISSUE TITLE
wrong file name

### ISSUE THREAD

**Issue by FabienZouaoui** [nextcloud/bruteforcesettings#13]
Hi,

This is not really an important issue, but the file name in the link to download application (from https://apps.nextcloud.com/apps/bruteforcesettings) is:
- https://github.com/nextcloud/bruteforcesettings/releases/download/v1.0.3/bruteforcesettings-1.0.2.tar.gz
and probably should be:
- https://github.com/nextcloud/bruteforcesettings/releases/download/v1.0.3/bruteforcesettings-1.0.3.tar.gz

Cheers,
--
Fabien Z.

**Comment by patschi** [comment]
This seems to be resolved since quite a while I guess, therefore closing this one. Feel free to re-open if it's not solved.
