### ISSUE TITLE
Brute force protect triggers  server error upgrade to 16.0.4

### ISSUE THREAD

**Issue by Milokita** [nextcloud/bruteforcesettings#151]
### Steps to reproduce
1. Input the wrong password 

### Expected behaviour
Web page shows wrong password

### Actual behaviour
**This happens after upgrading**
Web page returns server error and has to refresh before shows the page says wrong password 

### Server configuration

**Operating system**: Debian 9

**Web server:** Apache 2.7.3

**Database:** Mysql 10.3.15

**PHP version:** 7.3

**Nextcloud version:** 16.0.4.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Upgrade

**Where did you install Nextcloud from:** N/A

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
,"app":"index","method":"POST","url":"\/login","message":{"Exception":"Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException","Message":"An exception occurred while executing 'INSERT INTO `oc_bruteforce_attempts` (`action`, `occurred`, `ip`, `subnet`, `metadata`) VALUES(?, ?, ?, ?, ?)' with params [\"login\", 1567594207, \"137.189.241.15\", \"137.189.241.15\\\/32\", \"{\\\"user\\\":\\\"xingz\\\"}\"]:\n\nSQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value","Code":0,"Trace":[{"file":"\/var\/www\/html\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php","line":184,"function":"convertException","class":"Doctrine\\DBAL\\Driver\\AbstractMySQLDriver","type":"->","args":["An exception occurred while executing 'INSERT INTO `oc_bruteforce_attempts` (`action`, `occurred`, `ip`, `subnet`, `metadata`) VALUES(?, ?, ?, ?, ?)' with params [\"login\", 1567594207, \"137.189.241.15\", \"137.189.241.15\\\/32\", \"{\\\"user\\\":\\\"xingz\\\"}\"]:\n\nSQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value",{"errorInfo":["HY000",1364,"Field 'id' doesn't have a default value"],
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by TP75** [comment]
Sorry, but you list a very exotic software. Could I propose you to consider updating the a.m. list to the actual status? 

May I suggest using a more standard [Debian stable](https://www.debian.org/releases/) install?  Apparently, oldstable Debian 9 Jessie has most current [Apache 2.4.10-10+deb8u16](https://packages.debian.org/jessie/apache2)

Please consider this [advice in the forum](https://help.nextcloud.com/t/problems-with-nextcloud-php-on-my-lamp-server/63347/3?u=tp75)

**Comment by Milokita** [comment]
Thanks for the support, later I found out that when the program migrate me from owncloud, the database is not configure correctly all entry have the same id  I fixed it by manually reconfig the database
