### ISSUE TITLE
make 18 ready

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/bruteforcesettings#169]
This is a featured app, but not yet made 18-ready. Please don't let that get forgotten.

**Comment by wiswedel** [comment]
cc @rullzer

**Comment by duritong** [comment]
18 got released

**Comment by anthraxx** [comment]
@wiswedel i think it pretty much got forgotten

**Comment by wiswedel** [comment]
🏓 @rullzer

**Comment by rullzer** [comment]
Just a lot lower on the list than other stuff ;)
Done https://github.com/nextcloud/bruteforcesettings/releases/tag/v1.5.0
