### ISSUE TITLE
Greater control

### ISSUE THREAD

**Issue by c0fe** [nextcloud/bruteforcesettings#17]
Currently it appears that Brute Force settings from the Security tab is pretty limited in management. Perhaps add options to set the number attempts before lock out, how long the lock out is (if not permanent) and add captcha support?

**Comment by stefangweichinger** [comment]
Did you even find out the default number of attempts etc? I'd like to set that and find no docs at all.

**Comment by Killerhaschen** [comment]
The default value for MAX_ATTEMPTS is fixed in the Throttler.php file.
https://github.com/nextcloud/server/blob/174a550edb893c1211b65ee28ea46003f65a5716/lib/private/Security/Bruteforce/Throttler.php.
It is a constant, so it cannot be changed.
Unfortunately, a code change must first be made in the nextcloud server.

**Comment by mepreston** [comment]
i would like a setting to disable this.  i already use fail2ban and don't need to be looking in multiple apps for blockers.

**Comment by dik23** [comment]
> i would like a setting to disable this. i already use fail2ban and don't need to be looking in multiple apps for blockers.

Multiple methods of blocking is a good thing.  Security is done in layers.  If you really want to just disable the Brute-force settings app

**Comment by joshtrichards** [comment]
@mepreston To disable, use the `config.php` parameter [`auth.bruteforce.protection.enabled`](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#auth-bruteforce-protection-enabled)

@dik23 This app only manages the settings, but bruteforce protection itself is handled in `server` and must be disabled in the above mentioned parameter. Disabling this app merely makes it impossible to manage the whitelist/etc. from the web UI.

**Comment by joshtrichards** [comment]
Duplicate of #4
Created dedicated tracker for captcha support idea: #563
