### ISSUE TITLE
Not blocking bots

### ISSUE THREAD

**Issue by sandrockcstm** [nextcloud/bruteforcesettings#179]
Last night a bot made 100+ login attempts, for over an hour, using the username "PlcmSpIp."  There is no such user on my server, so there was never any real danger of them gaining access.  However, these login attempts were sometimes within 14 seconds of each other over the span of the hour, which in my mind should be enough trip the filter and time-out the IP address they're trying to log in from.

I've attached a picture to illustrate the problem.

![Bot Attempt](https://user-images.githubusercontent.com/29006563/77183537-78105480-6a9c-11ea-88f4-f5a9f68742af.JPG)

I don't know if this is someone figuring out how to *just barely* skirt the filter (there doesn't seem to be a way to view the filter rules) or if something is broken, but this seems a pretty critical problem to me.

**Comment by Sk1pp3r** [comment]
@sandrockcstm the logs from admin panel will log failed login attempts even when Nextcloud blocks that specific IP address... Check the `oc_bruteforce_attempts` table in your database to see if the `185.53.88.38` IP address is present there.

**Comment by sandrockcstm** [comment]
How do I do that?  A search of the documentation wasn't very helpful, and googling didn't turn anything up either.

**Comment by Sk1pp3r** [comment]
@sandrockcstm sorry for the late response, if you haven't found it yet.
You need to open your database and simply make a `select * from nextcloud..oc_bruteforce_attempts` and see if `185.53.88.38` is in there.

if you use MySQL as your database (or mariadb), then you can simply SSH into your device and check it. should be something like the following:

1. `ssh root@[your.device.IP.address]` (it will ask for password)
2. `mysql`
3. `use nextcloud;`
4. `select * from oc_bruteforce_attempts;`

**Comment by sandrockcstm** [comment]
@Sk1pp3r No worries, I figured you were busy with *gestures to everything*.

I'll give this a shot when I have some more free time, but for now I'm gonna close this and assume everything is working as intended.  Thanks for your help!
