### ISSUE TITLE
database table oc_bruteforce_attempts won't regenerate after deletion

### ISSUE THREAD

**Issue by Milokita** [nextcloud/bruteforcesettings#19]
Hi there,

 I recently deleted the table oc_bruteforce_attempts to fix the locking, but it seems it did not regenerate after that. Is there anything I can do?

**Comment by JSoko** [comment]
You shouldn't delete the table, just drop the entries next time.
Try to create the table oc_bruteforce_attempts new manualy.

**Comment by rullzer** [comment]
Yep deleting the table is not supported... try to recreate it.
Also the table is not part of this app but of the server.

**Comment by Ludovicis** [comment]
Hello,

I have the same problem
Can you help me please to recreate the table oc_bruteforce_attempts new manualy ?
With mariadb 10.1.26

Thanks,

**Comment by JSoko** [comment]
If you have a database backup, restore the table from the Backup and drop the entries...

If you don't have a backup... :-(

https://mariadb.com/kb/en/create-table/
or use phpmyadmin

**Comment by Ludovicis** [comment]
Thanks JSoko but my oc_bruteforce_attempts database was corrupted, i can't use my backup
I can use webmin but i don't know the prerequisite for recreate this table...
