### ISSUE TITLE
Delete Button missing

### ISSUE THREAD

**Issue by JochenFroehlich** [nextcloud/bruteforcesettings#217]
Hi, 
i'm running NC 19.0.2 and the Brute-force settings app in version 2.0.0
In the "settings -> security -> Brute-force IP whitelist" section I can add and see my whitlisted ip ranges but there is no button to delete them.
Can someone please have a look into this.

Thanks.

**Comment by mxkeke** [comment]
Same issue.

**Comment by michelebedin** [comment]
I've the same problem:
https://help.nextcloud.com/t/how-to-remove-an-ip-from-the-whitelist-of-brute-force/90946?u=michele1

**Comment by mxkeke** [comment]
Same issue
