### ISSUE TITLE
Restrict login to IP ranges part missing

### ISSUE THREAD

**Issue by JoAlsen** [nextcloud/bruteforcesettings#250]
Hi,

Updated to the version of Nextcloud 20.0.6. And now the Restrict login to IP ranges is missing in the settings for this app. Am I the only one seeing this issue? I can only see the Brute-force IP whitelist.

We hade it up and running on the previous version but since the upgrade it is no longer. See attached file.
![image](https://user-images.githubusercontent.com/78429134/106616984-75143a80-656e-11eb-855d-e14fa688f549.png)

**Comment by joshtrichards** [comment]
That's not this app, but it sounds like you're looking for the `limit_login_to_ip` / *Restrict login to IP addresses* app:

https://github.com/nextcloud/limit_login_to_ip

https://apps.nextcloud.com/apps/limit_login_to_ip
