### ISSUE TITLE
Missing Changelog for Brute-force settings 2.2.0

### ISSUE THREAD

**Issue by Franz-Heinz** [nextcloud/bruteforcesettings#328]
CHANGELOG.md is missing information about changes made to Brute-force settings with version 2.2.0.

**Comment by duck-rh** [comment]
and now for 2.3.0 too.
That is not very convenient if we have to read the full git history.

**Comment by joshtrichards** [comment]
Let's consolidate this into #500 since it's part of a broader issue.
