### ISSUE TITLE
Make app compatible with NC v23 

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/bruteforcesettings#335]
App management of NC says app is not compatible.

**Comment by leonardohlee** [comment]
follow up

**Comment by viceice** [comment]
PR already merged, needs a new release 😕 
- #333

**Comment by rakekniven** [comment]
As rullzer is not part of this project anymore I kindly ask @skjnldsv to do a release.

**Comment by skjnldsv** [comment]
On it, sorry

**Comment by skjnldsv** [comment]
done

**Comment by rakekniven** [comment]
Great! Thank you.
