### ISSUE TITLE
Issues with autoupload (iOS)

### ISSUE THREAD

**Issue by b-pfl** [nextcloud/bruteforcesettings#371]
It looks like the iOS autoupload feature of the official Nextcloud client does not work well with this App. 
I already created an issue at the client repository (https://github.com/nextcloud/ios/issues/2038), but maybe the App itself should rather take care of this?

**Comment by joshtrichards** [comment]
This app doesn't enforce the brute force settings, it merely allows adjustment of the settings. The actual logic/implementation is all in Server.

But if I understood the linked issues correctly, this seems like a client matter anyhow.
