### ISSUE TITLE
Make app compatible with NC v25

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/bruteforcesettings#407]
Today NC25 is out and this app needs some love ❤️ .

**Comment by vipergts450** [comment]
Any update on this from the maintainers?

**Comment by elpraga** [comment]
And thank you for working on it and making it available in the first place!

**Comment by nickvergessen** [comment]
This app is shipped with 25+ so it is there and compatible.

**Comment by nickvergessen** [comment]
Ah, so now I get it. You all get the warning/info in the admin settings that the app is not ready for 25, right?

**Comment by nickvergessen** [comment]
> Ah, so now I get it. You all get the warning/info in the admin settings that the app is not ready for 25, right?

Patch available at https://github.com/nextcloud/server/pull/35185
Can you try it?
https://docs.nextcloud.com/server/latest/admin_manual/issues/applying_patch.html#getting-a-patch-from-a-github-pull-request

The 26 patch should cleanly apply on 24 as well
