### ISSUE TITLE
Compatibility with nextcloud 25

### ISSUE THREAD

**Issue by magostinelli** [nextcloud/bruteforcesettings#421]
The update process of next cloud says that this extension is not compatible with version 25.

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/bruteforcesettings/issues/407

Please search before posting :)

**Comment by magostinelli** [comment]
> #407
> 
> Please search before posting :)

I tryed before open the case, but the search haven't found anything!

In any case, thanks!

**Comment by skjnldsv** [comment]
No worries
