### ISSUE TITLE
Release notes please?

### ISSUE THREAD

**Issue by BloodyIron** [nextcloud/bruteforcesettings#46]
Any chance we can get release notes added to releases when they come out, please? :)

**Comment by patschi** [comment]
I think the [CHANGELOG,md](https://github.com/nextcloud/bruteforcesettings/blob/master/CHANGELOG.md) does cover your needs? Therefore assuming this is solved. If not, feel free to re-open.

**Comment by BloodyIron** [comment]
I'm talking about in here -> https://github.com/nextcloud/bruteforcesettings/releases

Like every other github project, it's really nice to see the changes in the release notes on that page, instead of having to go hunt for them. If this could please do that, that'd be great!
