### ISSUE TITLE
Numbering of versions

### ISSUE THREAD

**Issue by dennisTGC** [nextcloud/bruteforcesettings#500]
We had some confusion about the versioning of the app and I think it could use some optimization. 

- In our Nextcloud v25 server, we found v2.5.0 of the app.
- On [the NC app store](https://apps.nextcloud.com/apps/bruteforcesettings) it reports version v2.4.0 as the latest for NC v24.
- In this project [the latest release](https://github.com/nextcloud/bruteforcesettings/releases) is v2.3.0 (on 17 dec. 2021). 
- The [Changelog.md](https://github.com/nextcloud/bruteforcesettings/blob/master/CHANGELOG.md) in all branches reports v2.4.0. 

I found the truth [here](https://github.com/nextcloud/bruteforcesettings/blob/stable25/appinfo/info.xml):
```
<version>2.5.0</version>
```

I think it has all to do with #407, but it's all very confusing, I would suggest cleaning it up:
- The actual status on the app store should not come from a comment I think. It's also very easy to assume the app is not supported anymore (we look often in the appstore at this view and missed the comment in the first viewing). As the app is fully supported and even a core app (supported when buying a subscription) I would suggest updating the appstore page. 
- Remove the releases/changelog, update it with new releases or point to where the info can be found. 

This issue is also related to #328.

**Comment by joshtrichards** [comment]
I agree. There are a mixture of contributing causes:

- App switched to shipped status with >=NC25 
- Release artifacts don't get generated *within* this repository any more (WIP)
  - Related: https://github.com/nextcloud-releases/bruteforcesettings (WIP)
- CHANGELOG simply isn't being maintained here any longer

There are other apps we need to take care of this for, but we should start somewhere.

To me the priority/tasks are:

1. Update the App Store entry to clarify the app is shipped now >=NC25 so store version is only the one kept around for <=NC24 environments
2. Officially deprecate the in-repo CHANGELOG for the time being (until/if someone chooses to maintain it)
3. Probably something related to making wrapping up release artifacts ending up in https://github.com/nextcloud-releases/bruteforcesettings then adding a note in *this* repo here to go there if one wants to check for release artifacts

We could probably just knock out 1 & 2 and backburner 3 until someone gets bored or something else makes it a priority.

I believe at the moment when `server` gets packaged, it's currently grabbing the appropriately tagged branch directly.

The release processes for shifting things to https://github.com/nextcloud-releases I think is still in early stages (understandable: there are a lot of apps to cover).
