### ISSUE TITLE
Still supported (NC28)?

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/bruteforcesettings#518]
Is this app support with Nextcloud 28?
The last release says "ready for NC23".....

We are at 28 :)

**Comment by joshtrichards** [comment]
It's a shipped app these days. It's definitely shipped with NC28. The version in there is v2.8.0:

https://github.com/nextcloud/bruteforcesettings/blob/daf611cbb49ecb375206293271e93530358a449c/appinfo/info.xml#L28

Where are you looking?

**Comment by Dennis1993** [comment]
Ok I saw it here in the release overview: https://github.com/nextcloud/bruteforcesettings/releases

last entry says: ready for NC 23 ☺️

**Comment by joshtrichards** [comment]
Yeah this app isn't using GitHub Releases for releases.

If you're curious you can always browse the tags or branches in the repo.

**Comment by joshtrichards** [comment]
Related: #500
