### ISSUE TITLE
Documentation Needed

### ISSUE THREAD

**Issue by DanielYWoo** [nextcloud/bruteforcesettings#58]
How does it work? A hacker could use shared IP pools with thousands of IPs which costs only 40$ monthly, so any protection against IP is useless. 
A Captcha or two-factor auth is much more useful to defend brute force attacks.  However, two-factor auth is very bad in user experience, so a built-in captcha will be good enough. Since we don't have any documentation I can only ask, how does this plugin work? Does it provide captcha? Or just simply IP rate limit?

**Comment by kaksikanaa** [comment]
Since we don't have any documentation I can only ask, how does this plugin work?
+1

**Comment by kesselb** [comment]
Brute force protection is a part of nextcloud/server. Check https://docs.nextcloud.com/server/17/admin_manual/configuration_server/bruteforce_configuration.html for more details. The `bruteforcesettings` app adds an interface to whitelist specific ip addresses.

**Comment by DanielYWoo** [comment]
That's good enough, thank you.
